// Generated by scripts/generate-placeholders.mts — do not edit by hand.
//
// Blur placeholders derived from the files in public/work/. Regenerate after
// replacing any image:
//
//   npx tsx scripts/generate-placeholders.mts

export const blurData: Record<string, string> = {
  "/work/amidx-technologies/cover.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTbzcfZAAAA",
  "/work/amidx-technologies/block-editor.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTbzcfZAAAA",
  "/work/amidx-technologies/crop-on-upload.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTbzcfZAAAA",
  "/work/sooth-bangladesh/cover.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTbzbWcAAAA",
  "/work/sooth-bangladesh/event-flow.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTbzeT/8QAA",
  "/work/sooth-bangladesh/catalogue-feed.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTbzeT/8QAA",
  "/work/hockerty-suit-designer/cover.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTb1W1H6QAA",
  "/work/hockerty-suit-designer/layer-composite.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTb0fSJeaAA",
  "/work/hockerty-suit-designer/option-compatibility.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTb0fSJeaAA",
  "/work/digital-products-store/cover.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTbzfYVmAAA",
  "/work/digital-products-store/deploy-pipeline.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTbzfYVmAAA",
  "/work/digital-products-store/admin-filament.png":
    "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTbzfYVmAAA",
  "/work/hr-group/cover.png":
    "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTTAAA=",
  "/work/hr-group/compliance.png":
    "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTTAAA=",
  "/work/hr-group/capability.png":
    "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTTAAA=",
  "/work/bees-bangladesh/cover.png":
    "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTTAAA=",
  "/work/bees-bangladesh/programme-record.png":
    "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTTAAA=",
  "/work/bees-bangladesh/document-archive.png":
    "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoQAAoAAwBSJaQAA3AA/vTTAAA=",
};
